server:
  port: 8081
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
zuul:
  routes:
    Authentication-ms:
      path: /Authentication-ms/**
      serviceId: Authentication-ms
      strip-prefix: false
  ignored-services: '*'
  prefix: /api

